### ISSUE TITLE
How do I close a client.ws conection?

### ISSUE THREAD

**Issue by marwernicke** [bitfinexcom/bitfinex-api-py#63]
I don't know how to close my websocket connection, so in case of an exception the program shuts down for being able to run again. 

#### Here is a simplified version of  code 
I just want to open the connection, wait a few seconds and then close it 
```
bfx = Client(API_KEY, API_SECRET)

@bfx.ws.on('all')
async def log_updates(notification):
      print(notification)

bfx.ws.run()
time.sleep(5)
bfx.ws.stop()
```

Can somebody tell me how to do this? I'm new to programming and have tried lots of stuff unsuccessfully

**Comment by JacobPlaster** [comment]
A close websocket function was added in this PR Fixed in https://github.com/bitfinexcom/bitfinex-api-py/issues/63.

Please see this example on how to use:

```
import os
import sys
sys.path.append('../../../')

from bfxapi import Client

bfx = Client(
  logLevel='DEBUG',
)

@bfx.ws.on('order_book_snapshot')
async def log_snapshot(data):
  print ("Snapshot: {}".format(data))
  # stop the websocket once a snapshot is received
  await bfx.ws.stop()

async def start():
  await bfx.ws.subscribe('book', 'tBTCUSD')

bfx.ws.on('connected', start)
bfx.ws.run()
```

**Comment by DmitriyG228** [comment]
Hi, this function works on specific event  like 'order_book_snapshot', but how to close connection from the main thread on demand?

**Comment by aemxn** [comment]
Hi. I'm still having issue on this. Can't interrupt with Ctrl+C on Windows 10 PowerShell.

```
bfx = Client()

@bfx.ws.on('error')
def log_error(err):
  print ("Error: {}".format(err))

@bfx.ws.on('new_candle')
def log_candle(candle):
  print ("New candle: {}".format(candle))

async def start():
  await bfx.ws.subscribe('candles', 'tBTCUSD', timeframe='30m')

  try:
    while True:
      time.sleep(60)
  except KeyboardInterrupt:
    print("Stopping...")
    await bfx.ws.stop()

bfx.ws.on('connected', start)
bfx.ws.run()
```

Python beginner here. Help me point where my mistake is. The try-except block I took from an answer on StackOverflow, but still couldn't make it stop by interrupting.
